language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - phpunit -v --configuration `pwd`/test/phpunit.xml

after_script:
  - ls -lR build
  - php vendor/bin/coveralls -v

notifications:
  email:
    - oleksii.mylotskyi@milsdev.com
