language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer install
  - composer update

script: phpunit -v --configuration `pwd`/test/phpunit.xml

after_script:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm

notifications:
  email:
    - oleksii.mylotskyi@milsdev.com
